import { Geist, Geist_Mono } from "next/font/google";
import NavLink from "./components/navLink";
import Logo from "./components/Logo";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Horizion Luxury Hotel",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header>
          <Logo />
          <NavLink />
        </header>
        {children}
      </body>
    </html>
  );
}
